# 1. CONEXÃO COM O BANCO DE DADOS
# O Spring usa as variáveis do Railway. Se não existirem, usa o seu MySQL do PC.
spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:railwaycr-doces}?createDatabaseIfNotExist=true
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:SUA_SENHA_DO_PC_AQUI}

# 2. CONFIGURAÇÕES DO HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 3. SEGURANÇA (JWT)
api.security.token.secret=${JWT_SECRET:ancelmo007}

# 4. PORTA
server.port=${PORT:8080}